# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDlg(object):
    def setupUi(self, LoginDlg):
        LoginDlg.setObjectName("LoginDlg")
        LoginDlg.resize(371, 257)
        LoginDlg.setStyleSheet("QDialog\n"
"{\n"
"    background-color: white;\n"
"}")
        self.idEdit = QtWidgets.QLineEdit(LoginDlg)
        self.idEdit.setGeometry(QtCore.QRect(60, 70, 251, 41))
        self.idEdit.setAutoFillBackground(False)
        self.idEdit.setStyleSheet("background-color: #E8F0FE;\n"
"border: 1px solid #DADFE3;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"font: 12pt \"나눔스퀘어\";")
        self.idEdit.setText("")
        self.idEdit.setObjectName("idEdit")
        self.pwEdit = QtWidgets.QLineEdit(LoginDlg)
        self.pwEdit.setGeometry(QtCore.QRect(60, 110, 251, 41))
        self.pwEdit.setStyleSheet("background-color: #E8F0FE;\n"
"border: 1px solid #DADFE3;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"font: 12pt \"나눔스퀘어\";")
        self.pwEdit.setObjectName("pwEdit")
        self.title = QtWidgets.QLabel(LoginDlg)
        self.title.setGeometry(QtCore.QRect(60, 30, 300, 31))
        self.title.setStyleSheet("font: 75 20pt \"나눔스퀘어 Bold\";")
        self.title.setObjectName("title")
        self.loginBtn = QtWidgets.QPushButton(LoginDlg)
        self.loginBtn.setGeometry(QtCore.QRect(60, 155, 251, 41))
        self.loginBtn.setStyleSheet("background-color:#0070AA;\n"
"border-radius: 10px;\n"
"font: 75 15pt \"나눔스퀘어 Bold\";\n"
"color: white;")
        self.loginBtn.setObjectName("loginBtn")
        self.signupBtn = QtWidgets.QPushButton(LoginDlg)
        self.signupBtn.setGeometry(QtCore.QRect(50, 201, 81, 16))
        self.signupBtn.setStyleSheet("font: 75 12pt \"나눔스퀘어 Bold\";\n"
"color: #0070AA;\n"
"background-color: #00000000")
        self.signupBtn.setObjectName("signupBtn")

        self.retranslateUi(LoginDlg)
        QtCore.QMetaObject.connectSlotsByName(LoginDlg)

    def retranslateUi(self, LoginDlg):
        _translate = QtCore.QCoreApplication.translate
        LoginDlg.setWindowTitle(_translate("LoginDlg", "Dialog"))
        self.title.setText(_translate("LoginDlg", "환영합니다!"))
        self.loginBtn.setText(_translate("LoginDlg", "로그인"))
        self.signupBtn.setText(_translate("LoginDlg", "회원가입"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDlg = QtWidgets.QDialog()
    ui = Ui_LoginDlg()
    ui.setupUi(LoginDlg)
    LoginDlg.show()
    sys.exit(app.exec_())
